AssignmentInConditionalCheck:    { }
CaseMissingElseCheck:            { }
ClassLineCountCheck:             
  line_count: 300 
ClassNameCheck:                  
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ClassVariableCheck:              {}
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
MethodNameCheck:                 
  pattern: !ruby/regexp /^[_a-z<>=\[|+-\/\*`]+[_a-z0-9_<>=~@\[\]]*[=!\?]?$/ 
ModuleLineCountCheck:            
  line_count: 300
ModuleNameCheck:          
  pattern: !ruby/regexp /^[A-Z][a-zA-Z0-9]*$/
ParameterNumberCheck:            
  parameter_count: 5